### ISSUE TITLE
Implementar API em GraphQL

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/backend#24]
## To-do

https://github.com/basedosdados/backend/pull/27
- [x] Implementar o endpoint do GraphQL
- [x] Implementar geração de schema para query automaticamente através dos modelos

https://github.com/basedosdados/backend/pull/28
- [x] Implementar geração de schema para mutations automaticamente através dos modelos
- [x] Query: Adicionar filtragem para campos de tabelas "pai"
- [x] Query: Adicionar filtragem por campos many-to-many
- [x] Mutation: Remover a necessidade de fornecer o ID nos `MutationPayload`
- [x] Mutation: Separação de mutations de `create` e `delete`

https://github.com/basedosdados/backend/pull/30
- [x] Mutation: Adicionar suporte à modificação de objetos
- [x] Mutation: Adicionar suporte a campos many-to-many
- [x] Implementar autenticação via JWT
- [x] Descontinuar endpoints REST
