### ISSUE TITLE
Melhorias nos modelos

### ISSUE THREAD

**Issue by rdahis** [basedosdados/backend#664]
Melhorias nos modelos já mapeadas:
- [x] Resolver a lentidão da página admin para `coverage.
- [x] Tornar os campos `on_delete` mais conservadores (evitar `CASCADE`) #644 
- [x] Adicionar `poll` ao Django Admin #661
- [x] Transformar o campo `dataset.organization` em ManyToMany. #371
- [x] Transformar os campos `table.cleaned_by` e `table.published_by` em ManyToMany. #372
- [x] Deletar o campo `table.raw_data_url`.
- [x] Deletar (ou tornar só `read-only`) os campos `dataset.page_views` e `table.page_views`.
- [x] Criar entidade `measurement_unit`. #174
- [x] Adicionar funcionalidade de `order` para `table.observation_level` #701

Algumas dessas já passaram por issues antigos. Com um esforço concentrado imagino que conseguimos matar várias rapidamente.
